version: "3.9"

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: mtb_postgis
    environment:
      POSTGRES_DB: mtbdb
      POSTGRES_USER: mtbuser
      POSTGRES_PASSWORD: mtbpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    build: .
    container_name: mtb_django
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    # Load env vars (DB, SECRET_KEY, DEBUG, etc.) from .env.docker
    env_file:
      - .env.docker
    environment:
      RUNNING_IN_DOCKER: "1"

volumes:
  pgdata:
